//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsumindoWS.WSConsultaReinfProd {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: O elemento de extensão WSDL opcional 'PolicyReference' do espaço para nome 'http://schemas.xmlsoap.org/ws/2004/09/policy' não foi tratado.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ConsultasReinf", Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultasReinf : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaInformacoesConsolidadasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultasReinf() {
            this.Url = global::ConsumindoWS.Properties.Settings.Default.Transmissor_do_EFD_Reinf__v1_4_WSConsultaReinfProd_ConsultasReinf;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaInformacoesConsolidadasCompletedEventHandler ConsultaInformacoesConsolidadasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sped.fazenda.gov.br/ConsultasReinf/ConsultaInformacoesConsolidadas", RequestNamespace="http://sped.fazenda.gov.br/", ResponseNamespace="http://sped.fazenda.gov.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaInformacoesConsolidadas(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento) {
            object[] results = this.Invoke("ConsultaInformacoesConsolidadas", new object[] {
                        tipoInscricaoContribuinte,
                        numeroInscricaoContribuinte,
                        numeroProtocoloFechamento});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaInformacoesConsolidadasAsync(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento) {
            this.ConsultaInformacoesConsolidadasAsync(tipoInscricaoContribuinte, numeroInscricaoContribuinte, numeroProtocoloFechamento, null);
        }
        
        /// <remarks/>
        public void ConsultaInformacoesConsolidadasAsync(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento, object userState) {
            if ((this.ConsultaInformacoesConsolidadasOperationCompleted == null)) {
                this.ConsultaInformacoesConsolidadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaInformacoesConsolidadasOperationCompleted);
            }
            this.InvokeAsync("ConsultaInformacoesConsolidadas", new object[] {
                        tipoInscricaoContribuinte,
                        numeroInscricaoContribuinte,
                        numeroProtocoloFechamento}, this.ConsultaInformacoesConsolidadasOperationCompleted, userState);
        }
        
        private void OnConsultaInformacoesConsolidadasOperationCompleted(object arg) {
            if ((this.ConsultaInformacoesConsolidadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaInformacoesConsolidadasCompleted(this, new ConsultaInformacoesConsolidadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultaInformacoesConsolidadasCompletedEventHandler(object sender, ConsultaInformacoesConsolidadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaInformacoesConsolidadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaInformacoesConsolidadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591