//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumindoWS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://preprodefdreinf.receita.fazenda.gov.br/WsREINF/RecepcaoLoteReinf.svc")]
        public string ConsumindoWS_wsReInf_RecepcaoLoteReinf {
            get {
                return ((string)(this["ConsumindoWS_wsReInf_RecepcaoLoteReinf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom-reinf.receita.fazenda.gov.br/WsREINF/ConsultasReinf.svc")]
        public string Transmissor_do_EFD_Reinf__v1_0_ConsultasReinf_ConsultasReinf {
            get {
                return ((string)(this["Transmissor_do_EFD_Reinf__v1_0_ConsultasReinf_ConsultasReinf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://reinf.receita.fazenda.gov.br/WsREINF/RecepcaoLoteReinf.svc")]
        public string Transmissor_do_EFD_Reinf__v1_4_WsReinfProd_RecepcaoLoteReinf {
            get {
                return ((string)(this["Transmissor_do_EFD_Reinf__v1_4_WsReinfProd_RecepcaoLoteReinf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://reinf.receita.fazenda.gov.br/WsREINF/ConsultasReinf.svc")]
        public string Transmissor_do_EFD_Reinf__v1_4_WSConsultaReinfProd_ConsultasReinf {
            get {
                return ((string)(this["Transmissor_do_EFD_Reinf__v1_4_WSConsultaReinfProd_ConsultasReinf"]));
            }
        }
    }
}
